services:
  db:
    image: postgres:16-alpine
    container_name: hrms_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hrms_db
    ports:
      - "5432:5432"
    volumes:
      - hrms_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hrms_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
    container_name: hrms_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:admin@db:5432/hrms_db"
      JWT_SECRET: "6de17084520dfd2d5a11b0b7f8bebb04383601ccd69085ea493e027a"
      EMAIL_HOST: "smtp.gmail.com"
      EMAIL_PORT: "587"
      EMAIL_USER: "your@gmail.com"
      EMAIL_PASS: "your-app-password"
      EMAIL_FROM: "WorkNest "
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
    depends_on:
      db:
        condition: service_healthy

volumes:
  hrms_db_data:
