export const ROUTES = {
  PUBLIC: {
    LOGIN: '/login',
    REGISTER: '/register',
    RESET_PASSWORD: '/reset-password',
    SET_PASSWORD: '/set-password',
  },
  DASHBOARD: {
    HR: {
      BASE: '/dashboard/hr',
      DASHBOARD: '/dashboard/hr',
      PROFILE: '/dashboard/hr/profile',
      SETTINGS: '/dashboard/hr/settings',
      NOTIFICATIONS: '/dashboard/hr/notifications',
      ORGANIZATION: '/dashboard/hr/organization',
      COMPANY_SETUP: '/dashboard/hr/company-setup',
      EMPLOYEES: {
        BASE: '/dashboard/hr/employees',
        LIST: '/dashboard/hr/employees',
        NEW: '/dashboard/hr/employees/new',
        DETAIL: (id: string) => `/dashboard/hr/employees/${id}`,
        EDIT: (id: string) => `/dashboard/hr/employees/${id}/edit`,
      },
      ATTENDANCE: {
        BASE: '/dashboard/hr/attendance',
        LIST: '/dashboard/hr/attendance',
        REPORTS: '/dashboard/hr/attendance/reports',
      },
      LEAVE: {
        BASE: '/dashboard/hr/leave',
        LIST: '/dashboard/hr/leave',
        CALENDAR: '/dashboard/hr/leave/calendar',
        TYPES: '/dashboard/hr/leave-types',
        POLICY: '/dashboard/hr/leave-policy',
      },
      HOLIDAYS: '/dashboard/hr/holidays',
      SHIFTS: '/dashboard/hr/shifts',
    },
    EMPLOYEE: {
      BASE: '/dashboard/employee',
      DASHBOARD: '/dashboard/employee',
      PROFILE: '/dashboard/employee/profile',
      ATTENDANCE: '/dashboard/employee/attendance',
      LEAVE: {
        BASE: '/dashboard/employee/leave',
        APPLY: '/dashboard/employee/leave',
        HISTORY: '/dashboard/employee/leave/history',
      },
      COMP_OFF: '/dashboard/employee/comp-off',
      OVERTIME: '/dashboard/employee/overtime',
      HOLIDAYS: '/dashboard/employee/holidays',
      EMPLOYEES: '/dashboard/employee/employees',
      NOTIFICATIONS: '/dashboard/employee/notifications',
      INBOX: '/dashboard/employee/inbox',
      HELP: '/dashboard/employee/help',
    },
  },
  HR: {
    BASE: '/hr',
    DASHBOARD: '/hr',
    PROFILE: '/hr/profile',
    SETTINGS: '/hr/settings',
    NOTIFICATIONS: '/hr/notifications',
    ORGANIZATION: '/hr/organization',
    COMPANY_SETUP: '/hr/company-setup',
    EMPLOYEES: {
      BASE: '/hr/employees',
      LIST: '/hr/employees',
      NEW: '/hr/employees/new',
      DETAIL: (id: string) => `/hr/employees/${id}`,
      EDIT: (id: string) => `/hr/employees/${id}/edit`,
    },
    ATTENDANCE: {
      BASE: '/hr/attendance',
      LIST: '/hr/attendance',
      REPORTS: '/hr/attendance/reports',
    },
    LEAVE: {
      BASE: '/hr/leave',
      LIST: '/hr/leave',
      CALENDAR: '/hr/leave/calendar',
      TYPES: '/hr/leave-types',
      POLICY: '/hr/leave-policy',
    },
    HOLIDAYS: '/hr/holidays',
    SHIFTS: '/hr/shifts',
  },
  EMPLOYEE: {
    BASE: '/employee',
    DASHBOARD: '/employee',
    PROFILE: '/employee/profile',
    ATTENDANCE: '/employee/attendance',
    LEAVE: {
      BASE: '/employee/leave',
      APPLY: '/employee/leave',
      HISTORY: '/employee/leave/history',
    },
    COMP_OFF: '/employee/comp-off',
    OVERTIME: '/employee/overtime',
    HOLIDAYS: '/employee/holidays',
    EMPLOYEES: '/employee/employees',
    NOTIFICATIONS: '/employee/notifications',
    INBOX: '/employee/inbox',
    HELP: '/employee/help',
  },
} as const;

export const API_ROUTES = {
  AUTH: {
    LOGIN: '/api/auth/login',
    REGISTER: '/api/auth/register',
    LOGOUT: '/api/auth/logout',
    REFRESH: '/api/auth/refresh',
  },
  COMPANY: {
    BASE: '/api/company',
    SETUP: '/api/company/setup',
  },
  EMPLOYEES: {
    BASE: '/api/employees',
    LIST: '/api/employees',
    CREATE: '/api/employees',
    DETAIL: (id: string) => `/api/employees/${id}`,
    UPDATE: (id: string) => `/api/employees/${id}`,
    DELETE: (id: string) => `/api/employees/${id}`,
  },
  ATTENDANCE: {
    BASE: '/api/attendance',
    LIST: '/api/attendance',
    CLOCK_IN: '/api/attendance/clock-in',
    CLOCK_OUT: '/api/attendance/clock-out',
    REGULARIZE: '/api/attendance/regularize',
  },
  LEAVE: {
    BASE: '/api/leave',
    APPLY: '/api/leave/apply',
    BALANCE: '/api/leave/balance',
    TYPES: '/api/leave/types',
    APPROVE: (id: string) => `/api/leave/${id}/approve`,
    REJECT: (id: string) => `/api/leave/${id}/reject`,
  },
} as const;



